### ISSUE TITLE
Artefacts when drawing characters on a retina display.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/graphics#1003]
Here's a screenshot of the artefacts from the conrod all_widgets example:

<img width="389" alt="screen shot 2015-09-08 at 12 46 50 am" src="https://cloud.githubusercontent.com/assets/4587373/9735800/c799e046-5680-11e5-9158-e162cd834de3.png">

(You may have to open the picture to full size to see them)

This doesn't seem to be an aliasing issue, but rather some sort of text scaling issue perhaps as they draw perfectly on a regular display?

@bvssvni also mentioned the possibility of them having something to do with texture interpolation along the edges?

**Comment by bvssvni** [comment]
I notice that the artifacts has the same color as assigned to the vertices. If the texture interpolates from transparent to the vertex color, then it would produce a similar artifact.

**Comment by bvssvni** [comment]
Getting this when I resize the window.

**Comment by bvssvni** [comment]
Seems to be a problem with opengl_graphics but not gfx_graphics.

**Comment by bvssvni** [comment]
The problem goes away when changing to NEAREST interpolation method.

**Comment by bvssvni** [comment]
Using `CLAMP_TO_EDGE` fixes the problem.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/opengl_graphics/pull/200

**Comment by mitchmindtree** [comment]
woooooohhoooooo!! can't wait to try it :smile_cat:
