### ISSUE TITLE
Add methods to calculate the on-screen position of GridCells in a Grid

### ISSUE THREAD

**Issue by tsujin** [PistonDevelopers/graphics#1013]
In my project, I implemented the following trait methods to extend the graphics::grid::Grid struct:
```rust
fn cell_position(&self, cell: (i32, i32)) -> (f64, f64) {
    (cell.0 as f64 * &self.units, cell.1 as f64 * &self.units)
}

fn x_pos(&self, cell: (i32, i32)) -> f64 {
    self.cell_position(cell).0
}

fn y_pos(&self, cell: (i32, i32)) -> f64 {
    self.cell_position(cell).1
}
```
These will allow me to easily get the position on the screen for any GridCell. So for example, if I have the grid `g = Grid { cols: 10, rows: 10, units: 25.0 }` and I want to draw a white square at (2, 2) on the grid, then I can use something like:
```rust
let square = rectangle::square(g.x_pos((2, 2)), g.y_pos((2, 2)), g.units)
let white_square = rectangle([1.0; 4], square, ... ) // last two args omitted from the rectangle function
/// ... draw white_square
```

There are likely much better ways than to calculate the positions than my functions, but the idea is what's important. This seems to make Grid easier to work with than it currently is so I think it would make sense for the library to already include these functions for the users.

**Comment by bvssvni** [comment]
Looks nice! The library uses arrays a lot so maybe it makes sense to use `[f64; 2]`?

**Comment by tsujin** [comment]
Should the method only return `[f64; 2]` and take `(u32, u32)` as an arg? It might make more sense because this is the type of the rows/cols in the `Grid` struct, and the `cells` method iterates through the grid cells as this type also. What do you think?

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/graphics/pull/1015
