### ISSUE TITLE
Re-export `TextureSettings` and `Rgb8Texture`?

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/graphics#1019]
This way a user wouldn't have to import the texture crate as well.

**Comment by bvssvni** [comment]
These are reexported in the graphics backends.

**Comment by mitchmindtree** [comment]
Yeah I noticed they were re-exported in the backends - the reason I thought it might be useful is because I've started looking into writing an `Image` primitive widget for conrod, and I thought these traits might be useful for working with textures (I haven't looked really closesly though). It's not a big problem though, I guess we can just import the texture crate to conrod too. twas just a suggestion :)

**Comment by bvssvni** [comment]
piston-graphics reexports `ImageSize`. I don't think `Rgba8Texture` and `TextureSettings` are needed.

**Comment by echochamber** [comment]
@bvssvni @michaelmera Is this issue resolved? If yes can we close the issue. Just want to clean up some of the cruft in the issues list 😄 .

**Comment by echochamber** [comment]
@mitchmindtree Thanks :)
