### ISSUE TITLE
Redesign `CharacterCache`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/graphics#1029]
As explained in https://github.com/PistonDevelopers/graphics/issues/1026.

- [x] Make `Character` take `&'a T` to the texture
- [x] Change CharacterCache::character to return Character<'a, T>

**Comment by mitchmindtree** [comment]
Maybe this could also be a good time to add support for multiple fonts? ([Related conrod issue](https://github.com/PistonDevelopers/conrod/issues/182))

**Comment by bvssvni** [comment]
Should we use `&str` for the font name?

Alternative is to store multiple caches, one for each font, in `conrod::Ui`.
