### ISSUE TITLE
Add a generic `GlyphCache`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/graphics#1033]
Currently, the graphics back-ends implements their own `GlyphCache`.

Since this library depends on piston-texture, we could create a generic `GlyphCache` that worked for all `CreateTexture`.

**Comment by bvssvni** [comment]
This would require a dependency on the Freetype binding or RustType. Perhaps this should be a separate library?

**Comment by mitchmindtree** [comment]
Yeah nice, this sounds great. I'd happy whether it was in this crate or its own (perhaps it could start in here and be moved out to its own if someone requests it?).

**Comment by bvssvni** [comment]
We only need a small interface for creating fonts, so perhaps we could add it as a trait?

On the other hand, if we use a separate library we could try different ones and let people choose which font library to use. Could put them in the same repo.

**Comment by bvssvni** [comment]
Some other ideas:

- Put the generic `GlyphCache` in Conrod
- Decouple 2D graphics and fonts, such that there is a small library defining the font abstraction with its own backends

**Comment by bvssvni** [comment]
It would be nice to have a `GlyphCache` that supported multiple fonts.

Another use case is to extract cubic Bezier splines from a glyph and use it for effects.
