### ISSUE TITLE
Implement sprite batching

### ISSUE THREAD

**Issue by crumblingstatue** [PistonDevelopers/graphics#1041]
It would be nice to have a fast way of drawing lots of sub-textures from a texture atlas. Something similar to https://love2d.org/wiki/SpriteBatch.

This would be useful for efficient rendering of things like tile maps or certain particle effects.

**Comment by bvssvni** [comment]
We just recently started optimizing, and texture rendering has not been worked on yet. I think it is possible to a similar optimization technique as for the colored graphics. See https://github.com/PistonDevelopers/gfx_graphics/pull/286. This will reduce draw calls for the same texture.
