### ISSUE TITLE
Documentation is not up to date

### ISSUE THREAD

**Issue by Kerosene2000** [PistonDevelopers/graphics#1049]
Nope, it is not 😄

**Comment by echochamber** [comment]
@Kerosene2000 Any places you are referring to specifically?

**Comment by Kerosene2000** [comment]
Online doc:
<img width="1434" alt="capture d ecran 2016-07-05 a 22 07 51" src="https://cloud.githubusercontent.com/assets/3610253/16598235/2d32e826-42fd-11e6-8d15-6f81cbd4487b.png">

Local doc generated by `cargo doc`:
<img width="1419" alt="capture d ecran 2016-07-05 a 22 08 03" src="https://cloud.githubusercontent.com/assets/3610253/16598254/3fda70b6-42fd-11e6-90cf-2d4de284bd68.png">

**Comment by echochamber** [comment]
Ah, thanks for clarifying. I think if you make a PR on the [docs repo](https://github.com/PistonDevelopers/docs/tree/gh-pages/graphics) with the updated graphics docs it should fix that.

**Comment by Kerosene2000** [comment]
Here it is https://github.com/PistonDevelopers/docs/pull/6 !

**Comment by echochamber** [comment]
@bvssvni I believe this can be closed now.

**Comment by echochamber** [comment]
ty @Kerosene2000 :)
