### ISSUE TITLE
Formula for rectangle::centered is incorrect

### ISSUE THREAD

**Issue by robbieh** [PistonDevelopers/graphics#1079]
According to the docs: "use x, y, half-width, half-height". Thus it needs to be:
    [rect[0] - rect[2], rect[1] - rect[3],  rect[0] + rect[2], rect[1] + rect[3]]

Or else the docs need to be updated to reflect what the current code really does.

**Comment by bvssvni** [comment]
The code is correct. You're thinking of a rectangle storing max/min coordinates.

**Comment by robbieh** [comment]
I'm afraid I don't understand. What is this supposed to do if not construct a rectangle centered at x,y with width (2 * half-width) and height (2 * half-height)?

**Comment by bvssvni** [comment]
For example:

```
// cx + hw
rect[0] + rect[2]
```

This would be the right edge with a rectangle storing max/min coordinates. However, Piston-Graphics uses the format `[x, y, w, h]`, so the correct formula is:

```
2.0 * rect[2]
```

**Comment by robbieh** [comment]
Got it. Thank you!
