### ISSUE TITLE
Scaling graphics causes artifacting

### ISSUE THREAD

**Issue by KongouDesu** [PistonDevelopers/graphics#1104]
I'm trying to make piston scale my graphics automatically, but it seems to cause some wierd artifacting. 

What I'm trying to do is cause my coordinate space to be stretched to fit the size of the window, without changing the coordinates. 
I'm currently using this code to scale it, which does work:
``c.transform = c.transform.scale(
                args.width as f64 / 1920., args.height as f64 / 1080.
            );
``
Where args is "RenderArgs" and c is "Context". This causes everything everything to be sized and positioned relatively with 1920x1080 being the lower left corner.
However, it causes some serious artifacting.
This image (the image is only the black part and has no white in it)
![image](https://user-images.githubusercontent.com/25505176/43920611-b2b54cc4-9c19-11e8-9bed-e125f347e9b9.png)
Turns into this (again, blue is just a background)
![image](https://user-images.githubusercontent.com/25505176/43920185-8077d958-9c18-11e8-849a-d7080c09a9a9.png)
When the window size is 1900 by 1000. The issue is present even downscaling by eg. 0.5x.
In fact, this happens even if the window is 1920 by 1080 and no scaling should happen.

The issue might be solved by using a Viewport, but it doesn't seem obvious to me how it's supposed to be used, and I couldn't get it to work properly when trying.

Is this because I'm scaling it incorrectly, not using a viewport, or a bug?

**Comment by bvssvni** [comment]
Closed since https://github.com/PistonDevelopers/opengl_graphics/issues/289 says this is due to white transparent pixels.
