### ISSUE TITLE
XOR'd lines and shapes?

### ISSUE THREAD

**Issue by moonheart08** [PistonDevelopers/graphics#1105]
Support for drawing via XOR would be nice. This is something that is often used when making, say, a "transparent" cursor, where contrast might be an issue.

**Comment by bvssvni** [comment]
Did you mean `Blend::Invert`? https://docs.rs/piston2d-graphics/0.26.0/graphics/draw_state/enum.Blend.html

**Comment by moonheart08** [comment]
Yup, thanks. Guess i'm just blind.

**Comment by bvssvni** [comment]
Closing.
