### ISSUE TITLE
Add depth support

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/graphics#824]
The current design causes problems when the order of rendering needs to be swapped.

- [ ] Add `fn depth(&mut self, depth: Option<f32>);`
- [ ] Add `fn clear_depth(&mut self, f32);`

**Comment by bvssvni** [comment]
Perhaps when z-depth is set to `None`, the semi-transparent triangles should be ignored, but no flushing is done. The triangles stays in the buffer until `z_flush` is called.

**Comment by bvssvni** [comment]
In HTML, a z-index of 1 is on top of a z-index of 0. If we follow this convention, then `0.0` should be far clip distance and `1.0` should be near clip distance.

**Comment by bvssvni** [comment]
opengl_graphics probably need another uniform variable for the z-depth and set the z-value in the vertex shader.

**Comment by bvssvni** [comment]
`z_flush` could be implemented on a wrapper back-end.

**Comment by bvssvni** [comment]
It might be possible to set the z-depth in fragment shader and thereby work around the limitation with perspective projections.

**Comment by bvssvni** [comment]
I'm having second thoughts about this, because depth is not used directly within the library. It is a benefit of keeping the back-end abstraction as small as possible. Perhaps we could decouple this?

**Comment by bvssvni** [comment]
One idea is to allow a 3D transform in column major f32 4x4 matrix, which could be added as parameter to the `Graphics` trait. This could be a separate method or in a new `Graphics3D` trait.

**Comment by bvssvni** [comment]
Hmm... I don't think we should add depth support at this point. Better wait until we have a use case.

Closing.

**Comment by dylanbraithwaite** [comment]
Hi, 
Just wondering what the chances of getting this reopened are? It seems like you were considering only adding internal support for depth originally, but it would be very useful to be able to directly specify depth in the api.

It's really the only solution (other than resorting the list of entities every frame) for "2.5D" games where you want to depth sort sprites based on their y-coordinates to imitate actual depth, like this:
![eg](https://i.imgur.com/Vl214QT.gif)
