### ISSUE TITLE
Make types::Rectangle a struct

### ISSUE THREAD

**Issue by dcampbell24** [PistonDevelopers/graphics#882]
I would like to make internal::rectangle a proper type so that methods can be implemented on it, type safety can be enforced, and getting values from the array is easier to read. This type could also then be exported rather than wrapping the type alias with a tuple struct and exporting that.  

Regarding the methods, I think it would be nice to have some methods for doing things like determining whether a point is inside of the rectangle. I am not sure whether this kind of functionality should really live in this library or somewhere else, but it would be nice to have one place for these functions to live rather than repeating them in different code bases.

**Comment by bvssvni** [comment]
Can use `Rect`.

`Rectangle` is an object which draws the rectangle, but `Rect` is the property type.

**Comment by bvssvni** [comment]
Another possibility is to implement `Rectangled` directly for `internal::rectangle`.

**Comment by bvssvni** [comment]
The trait `Transformed` is implemented for `vecmath::Matrix2d`, which is `[ax, ay, tx, bx, by, ty]`. This a common layout for 2D transform matrices.

Similarly, a rectangle is often stored `[x, y, w, h]`.

**Comment by bvssvni** [comment]
It might happen that the property types become replaced by impl methods, so instead of `.set(Rect([x, y, w, h]))` we get `.rect([x, y, w, h])`.

**Comment by zummenix** [comment]
I agree with @dcampbell24  to have proper types with methods. `Rect`, `Point`, `Size` should be structs.

**Comment by bvssvni** [comment]
Can we use the `From` trait to get automatic conversion from tuples and arrays?

**Comment by Potpourri** [comment]
@bvssvni no, we can't impl foreign trait for arbitrary types.

**Comment by bvssvni** [comment]
@Potpourri but it would work with a `Rect` struct?

**Comment by Potpourri** [comment]
Yes.

**Comment by bvssvni** [comment]
That would be nice.

**Comment by bvssvni** [comment]
I deleted some of my comments because they were about the old design.

**Comment by dcampbell24** [comment]
I just created a PR with my thoughts on what a Rectangle struct might look like. It makes use of the From trait and also implements Mul and Add for scaling and translation.

**Comment by dcampbell24** [comment]
Closing since the Rect struct has been merged.
