### ISSUE TITLE
Upgrade/redesign to Rust beta

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/graphics#884]
This requires redesigning because piston-quack no longer works.

- [x] Get rid of slice_patterns
- [x] Move to `num::Float`
- [x] Remove property methods on `Context`, since members are public
- [x] Make `Transformed` take `self` by value
- [x] Implement `Transformed` for `Context`
- [x] Make `ViewTransform` take `self` by value, implement it for `Context`
- [x] Move `Transformed` to its own module
- [x] Move `ViewTransform` methods to `Context`, remove `ViewTransform`
- [x] Make `Context::get_view_size` return `Vec2d`
- [x] Remove old reexported names (since everything breaks anyway)
- [x] Rename `vecmath` to `math`
- [x] Remove dependency on piston-quack
- [x] Implement `Colored` for `internal::Color`
- [x] Make `Colored` take `self` by value
- [x] Delete `Transform` property type
- [x] Delete `ViewTransform` property type
- [x] Delete `ellipse::MaybeBorder` property type
- [x] Rename `Ellipse::border` to `Ellipse::new_border`
- [x] Add builder methods to `Ellipse`
- [x] Rename `Image::colored` to `Image::new_colored`
- [x] Add builder methods to `Image`
- [x] Rename `Rectangle::round` to `Rectangle::new_round`
- [x] Rename `Rectangle::border` to `Rectangle::new_border`
- [x] Rename `Rectangle::round_border` to `Rectangle::new_round_border`
- [x] Add builder methods to `Rectangle`
- [x] Remove `rectangle::MaybeBorder`
- [x] Remove `line::Radius`
- [x] Remove `line::Width`
- [x] Rename `Line::round` to `Line::new_round`
- [x] Add builder methods for `Line`
- [x] Implement `Colored` for `Line`
- [x] Implement `Colored` for `Ellipse`
- [x] Implement `Colored` for `Rectangle`
- [x] Move `Colored` to its own module

**Comment by bvssvni** [comment]
- [ ] Remove Cargo.dot, update dependency graph

**Comment by Ryman** [comment]
@bvssvni Awesome work! Thanks!

**Comment by bvssvni** [comment]
Done :)
