### ISSUE TITLE
Move `shapes` to another library

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/graphics#940]
cc @dcampbell24 

I'd like to stabilize piston-graphics, and one way to make this easier is to refactor out the parts that are likely to change.

Since we are using `Into<[T; N]>` we can move `shapes` to another library.

**Comment by dcampbell24** [comment]
Seems reasonable to me. My only concern is the every growing number of libraries in Piston. For a newcomer it can be somewhat overwhelming to figure out what combination of libraries they are supposed to use when they just want whatever will work.

**Comment by bvssvni** [comment]
Yeah, it is a problem figuring out what to use. Others solve this by putting everything in one huge library.

**Comment by bvssvni** [comment]
@dcampbell24 I moved the structs to https://github.com/pistondevelopers/shapes
