### ISSUE TITLE
What is the future of graphics?

### ISSUE THREAD

**Issue by dcampbell24** [PistonDevelopers/graphics#945]
I am kind of curious where this library is headed in consideration of the growth gfx. Now that gfx is an abstraction over graphics back-ends is there any reason for this library to also be an abstraction over back-ends rather than just building on top of gfx?

I am also curious whether this library would get better performance by drawing things like non-filled rectangles using lines rather than triangles? Are there other optimizations that could be realized by using the larger feature set of gfx?

**Comment by kvark** [comment]
@dcampbell24 gfx-rs is indeed growing, but Glium is growing even faster. In this light, Piston's best strategy would be to be polymorphic over Gfx/Glium/GL, which is exactly what it's doing now - cooperating with everyone.

Keep in mind that some users would want to use piston-graphics mixed with their own custom drawing, in which case they might have different preferences over the back-end.

Non-filled triangles are definitely a good way to get the performance, though I'm not sure if this use case is large enough for Piston to provide separate API for.

As for the other optimizations, instancing comes to mind, but I have no idea how graphics is going to provide that. I don't think the performance is the primary goal, but rather the simplicity and convenience are.

@bvssvni please correct me

**Comment by bvssvni** [comment]
I have written 2D animation software for many years and piston-graphics is an attempt to solve the problems I had:

- Software rasterization is too slow for many simple operations
- Users want better responsiveness when working with complex scenes
- Least square deforming of images gives a style with nice results from little effort
- I want to be able to mix 2D and 3D
- There is a benefit in having a simple abstraction with low hardware requirements
- People have problems with installing on old hardware, you need alternatives
- Targeting new platforms, devices and experiment with new APIs without rewriting the whole thing
- Triangles are better for clipping than basing the clipping algorithm on polygons
- Libraries for using animations in games (People using my software has been #1 in App Store)
- I want to make it easier to write custom widgets

piston-graphics is perfect for me and the kind of software I want to build.

The question you are asking is why not just use Gfx? 3D changes every 5th year or so, and I there will be new hardware popping up replacing the old one. However, the requirement for 2D stays almost the same.

**Comment by bvssvni** [comment]
@dcampbell24 Please open up a new issue if you want to discuss unfilled triangles.

I have not thought of instanced rendering, but at some point you have to choose between the simplicity of this design and raw performance. Nothing stops you from combining both approaches.

I am going to close this, because I think we have listed good enough reasons for piston-graphics.
