### ISSUE TITLE
Add examples for rustdoc

### ISSUE THREAD

**Issue by Esption** [PistonDevelopers/graphics#953]
I had a bit of fun trying to figure out how to use this.  I eventually managed to figure out how to draw a texture, but it would be quite nice if you added some examples for the in-line doc.

Wrote one for Image and I can do it for others, if it's wanted / I can figure this stuff out well enough.

EDIT: Ah, sorry.  I've never sent a PR or opened an issue before, but here's the PR bit. https://github.com/PistonDevelopers/graphics/pull/954  I should have just done a PR and left the comment there, it seems.

**Comment by bvssvni** [comment]
You did fine! Opening issues before PR is good.

**Comment by bvssvni** [comment]
We had some problems with checking the examples, because it needs to use a back-end to compile. More examples could be sent to https://github.com/pistondevelopers/piston-examples.

Closing.
