### ISSUE TITLE
Rename `Text::colored` to `Text::new_colored`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/graphics#980]
This will make it more consistent with `Image::new_colored`.

**Comment by Vinatorul** [comment]
Does this change require to update all piston project immediately, or we'd have to support both syntax for some time?

**Comment by bvssvni** [comment]
We can support both and add a comment `/// DEPRECATED` on `Text::colored`.

However, I don't think this is thought through well enough, opened https://github.com/PistonDevelopers/graphics/issues/993.

**Comment by bvssvni** [comment]
Closed in favor of https://github.com/PistonDevelopers/graphics/issues/993
