### ISSUE TITLE
More user-friendly functions in lib.rs

### ISSUE THREAD

**Issue by Vinatorul** [PistonDevelopers/graphics#987]
I think it will be much more easier to work with library, if it will have more easy-to-use functions.
Now there are:
* `circle_arc`
* `clear`
* `ellipse`
* `image`
* `polygon`
* `rectangle`

I think it will be nice to use
* `text` instead of `text::Text::draw`
* `line` instead of `line::Lite::draw`
* etc

Short example for text:
now:
```
piston_window.draw_2d(|c, g| {
    clear([0.0, 0.0, 0.0, 1.0], g);
    rectangle([1.0, 0.0, 0.0, 1.0], [0, 0, 100, 100], c.transform, g);
    let transform = c.transform.trans(150, 150);
    text::Text::colored([1.0, 1.0, 1.0, 1.0], 32).draw("my text", &mut glyphs, &c.draw_state,  transform, g);
}
```
after:
```
piston_window.draw_2d(|c, g| {
    clear([0.0, 0.0, 0.0, 1.0], g);
    rectangle([1.0, 0.0, 0.0, 1.0], [0, 0, 100, 100], c.transform, g);
    text([1.0, 1.0, 1.0, 1.0], [150, 150], "my text", &mut glyphs, &c, g);
}
```
If you will like this idea - I can implement a bunch of such functions and create a PR for further discussion.

**Comment by bvssvni** [comment]
Good idea!

Notice that the shortcuts use the default draw state but takes a transform argument. So, for `text` it should be like this:

```
text([1.0, 1.0, 1.0, 1.0], [150, 150], "my text", &mut glyphs, c.transform, g);
```

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/graphics/pull/990
